
trigger:
- master

pool: 'AzureVms'

steps:

- task: ExecuteLoadRunnerProfessional@0
  inputs:
    SourcePath: 'C:\Scenarios'
    TreatFailuresAsErrors: false
    PublishArtifactsManually: true
    BuildArtifactsDirectory: 'C:\Artifacts'
    PublishTestReportsManually: true
    BuildTestReportsDirectory: 'C:\Reports'

- task: ExecuteLoadRunnerProfessional@0
  inputs:
    SourcePath: 'C:\Scenarios2'
    TreatFailuresAsErrors: false
    PublishArtifactsManually: true
    BuildArtifactsDirectory: 'C:\Artifacts'
    PublishTestReportsManually: true
    BuildTestReportsDirectory: 'C:\Reports'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'C:\Artifacts'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*Report.xml'
    searchFolder: 'C:\Reports'
    mergeTestResults: true