
trigger:
- master

pool: 'AzureVms'

steps:

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*'
    searchFolder: 'C:\Reports'
    mergeTestResults: true
    testRunTitle: 'LoadRunner'